### ISSUE TITLE
Logo for  Sunspotter Citizen Science Challenge

### ISSUE THREAD

**Issue by kellinora** [zooniverse/Sunspots#12]
To feature on Sunspotter and will also use this on signage for the Adler floor facilitation of this on August 29th at Summer of Science - Power of the Crowd.  Description of the facilitated program - 

As part of the Adler's Summer of Science activities floor facilitators will Adler invites guests to, as Sarcastic Rover says, “Do a science”, by joining in Zooniverse’s Summer Sunspotter Citizen Science Challenge (try saying that three times fast).  From 8/29- -9/5.  Zooniverse volunteers will be challenged to contribute 250,000 classifications to the Sunspotter (sunspotter.org) online citizen science project.  Sunspotter enlists volunteers to rank the complexity of sunspot groups to predict how the Sun's magnetic activity affects us on Earth.

**Comment by heathv** [comment]
Still a work in progress, but I wanted to provide some sort of update to this.

![sunspot-citsci-logo](https://cloud.githubusercontent.com/assets/4551411/9477431/dae3fe60-4b37-11e5-8503-50633a347303.jpg)

**Comment by kellinora** [comment]
Thanks Heath.  Let me know when this is done.  Adler social media is going to share all this out as part of the summer of science stuff.  WOOOOOO!

**Comment by heathv** [comment]
This should be the final. If this works let me know and I'll generate the assets. If not, I'll try to fix it!

![citscisuns](https://cloud.githubusercontent.com/assets/4551411/9503232/51409cc6-4bfb-11e5-9545-28b3aff53de1.jpg)

**Comment by kellinora** [comment]
These are great.  Asset generate away.

On Wed, Aug 26, 2015 at 2:05 PM, Heath V <notifications@github.com> wrote:

> This should be the final. If this works let me know and I'll generate the
> assets. If not, I'll try to fix it!
>
> [image: citscisuns]
> <https://cloud.githubusercontent.com/assets/4551411/9503232/51409cc6-4bfb-11e5-9545-28b3aff53de1.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zooniverse/Sunspots/issues/12#issuecomment-135141929>.
>



-- 
Citizen Science Education Lead
Adler Planetarium

**Comment by heathv** [comment]
Two different versions at two different sizes. They're labeled 'for dark' and 'for light' too for whatever purpose they're used.

![sunspots-citsci-fordark-large](https://cloud.githubusercontent.com/assets/4551411/9505571/df5ea96e-4c08-11e5-8fbc-023329bcb86c.png)
![sunspots-citsci-fordark](https://cloud.githubusercontent.com/assets/4551411/9505568/df5ab0ca-4c08-11e5-95fb-45e518269b00.png)
![sunspots-citsci-forlight-large](https://cloud.githubusercontent.com/assets/4551411/9505569/df5b5430-4c08-11e5-98a7-97b77f0b7d7a.png)
![sunspots-citsci-forlight](https://cloud.githubusercontent.com/assets/4551411/9505570/df5c1ba4-4c08-11e5-88bf-5ecb86e9800f.png)

**Comment by parrish** [comment]
I'm assuming this goes on the front page?

**Comment by parrish** [comment]
I assumed it did: http://www.sunspotter.org/staging/
