### ISSUE TITLE
Banner/Counter - Sunspotter Citizen Science Challenge

### ISSUE THREAD

**Issue by kellinora** [zooniverse/Sunspots#13]
Design a banner to feature on Sunspotter home for the Sunspotter Citizen Science Challenge (8/29-9/5)

**Comment by heathv** [comment]
Hopefully this fits the bill. I envisioned the banner itself being a progress with a marker at the current level. Would be cool if on page load the fill could be animated.

![sunspot-citsci-banner](https://cloud.githubusercontent.com/assets/4551411/9476949/2cfede70-4b35-11e5-93b4-003cd71c0f57.jpg)

**Comment by kellinora** [comment]
Pretty!

On Tue, Aug 25, 2015 at 2:27 PM, Heath V <notifications@github.com> wrote:

> Hopefully this fits the bill. I envisioned the banner itself being a
> progress with a marker at the current level. Would be cool if on page load
> the fill could be animated.
>
> [image: sunspot-citsci-banner]
> <https://cloud.githubusercontent.com/assets/4551411/9476949/2cfede70-4b35-11e5-93b4-003cd71c0f57.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zooniverse/Sunspots/issues/13#issuecomment-134708536>.
>



-- 
Citizen Science Education Lead
Adler Planetarium

**Comment by chrissnyder** [comment]
How's this? http://www.sunspotter.org/staging/

**Comment by kellinora** [comment]
Looks great to me.

Thanks,
Kelly

On Tue, Aug 25, 2015 at 9:52 PM, Chris Snyder <notifications@github.com>
wrote:

> How's this? http://www.sunspotter.org/staging/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zooniverse/Sunspots/issues/13#issuecomment-134801373>.
>



-- 
Citizen Science Education Lead
Adler Planetarium

**Comment by parrish** [comment]
I ended up changing the numeric color to white to match the site and be more legible.
